main/urls.py
from django.urls import path
from .views import *

app_name = "main"

urlpatterns = [
    path("", showmain, name="mainpage"),
    path("show/", showhw, name="show"),
    path("introduce/", introduce, name="introduce"),
    path("post/", post, name="post"),
    path("<str:id>", detail, name="detail"),
    path("new/", new, name="new"),
    path("create/", create, name="create"),
    path("edit/<str:id>", edit, name="edit"),
    path("update/<str:id>", update, name="update"),
    path("delete/<str:id>", delete, name="delete"),
    path("<str:post_id>/create_comment", create_comment, name="create_comment"),
    path("edit_comment/<str:id>", edit_comment, name="edit_comment"),
    path("update_comment/<str:id>", update_comment, name="update_comment"),
    path("delete_comment/<str:id>", delete_comment, name="delete_comment"),
    path("like_toggle/<str:post_id>", like_toggle, name="like_toggle"),
    path("dislike_toggle/<str:post_id>", dislike_toggle, name="dislike_toggle"),
]

sns_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include("allauth.urls")),
    path("users/", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = "users"

urlpatterns = [
    path("<int:id>/mypage", views.mypage, name="mypage"),
    path("<int:id>/follow", views.follow, name="follow"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    followings = models.ManyToManyField(
        "self", related_name="followers", symmetrical=False
    )


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from main.models import Post
from django.contrib.auth.models import User

# Create your views here.
def mypage(request, id):
    user = get_object_or_404(User, pk=id)
    context = {
        "user": user,
        "posts": Post.objects.filter(writer=user),
        "followings": user.profile.followings.all(),
        "followers": user.profile.followers.all(),
    }
    return render(request, "users/mypage.html", context)


def follow(request, id):
    user = request.user
    followed_user = get_object_or_404(User, pk=id)
    is_follower = user.profile in followed_user.profile.followers.all()
    if is_follower:
        user.profile.followings.remove(followed_user.profile)
    else:
        user.profile.followings.add(followed_user.profile)
    return redirect("users:mypage", followed_user.id)

users/templates/users/mypage.html
{%extends 'base.html'%}{%load static%}{%block content%}
<section class="pagesec">
{%if request.user.is_authenticated%}
<div class="container">
    <h1>
        {% if 'user' in user.username and user.username != 'user' %}
            {{ user.last_name }}{{ user.first_name }}
        {% else %}
            {{ user.username }}
        {% endif %}
    {% if request.user != user %}<!--다른 사람의 프로필에 들어온 경우에만 팔로우/언팔로우 버튼이보임-->
        {% if request.user.profile in user.profile.followers.all %}
            <a href="{%url 'users:follow' user.id %}"><button type="button" class="btn btn-outline-info">언팔로우</button></a>
        {% else %}
            <a href="{%url 'users:follow' user.id %}"><button type="button" class="btn btn-info">팔로우</button></a>
        {% endif %}
    {% endif %}
    </h1>

    <div class="container">
        <h5>팔로워{{user.profile.followers.count}}명</h5>
        {%for follower in user.profile.followers.all %}
            <a href="{% url 'users:mypage' follower.user.id %}">{{follower.user.username}}</a>
        {% endfor %}
        <h5>팔로잉{{user.profile.followings.count}}명</h5>
        {% for following in user.profile.followings.all %}
            <a href="{%url 'users:mypage' following.user.id%}">{{following.user.username}}</a>
        {% endfor %}
        </div>
    <div>

    <div>
        {%for post in posts%}
            <h3><a href="{%url 'main:detail' post.id%}">{{post.title}}</a></h3><br>
            {{post.summary}}
            <hr>
        {%endfor%}
    </div>
</div>
{%else%}
<h3>로그인 후 이용 가능</h3>
<a href="{%url 'account_login'%}" class="btn btn-warning">로그인</a>
<a href="{%url 'account_signup'%}" class="btn btn-warning">회원가입</a>
{%endif%}
</section>
{%endblock%}