main/urls.py
from django.urls import path
from .views import *

app_name = "main"

urlpatterns = [
    path("", showmain, name="mainpage"),
    path("show/", showhw, name="show"),
    path("introduce/", introduce, name="introduce"),
    path("post/", post, name="post"),
    path("<str:id>", detail, name="detail"),
    path("new/", new, name="new"),
    path("create/", create, name="create"),
    path("edit/<str:id>", edit, name="edit"),
    path("update/<str:id>", update, name="update"),
    path("delete/<str:id>", delete, name="delete"),
    path("<str:post_id>/create_comment", create_comment, name="create_comment"),
    path("edit_comment/<str:id>", edit_comment, name="edit_comment"),
    path("update_comment/<str:id>", update_comment, name="update_comment"),
    path("delete_comment/<str:id>", delete_comment, name="delete_comment"),
    path("like_toggle/<str:post_id>", like_toggle, name="like_toggle"),
    path("dislike_toggle/<str:post_id>", dislike_toggle, name="dislike_toggle"),
]

sns_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include("allauth.urls")),
    path("users/", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = "users"

urlpatterns = [
    path("<int:id>/mypage", views.mypage, name="mypage"),
    path("<int:id>/follow", views.follow, name="follow"),
]

main/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    summary = models.CharField(max_length=25, null=True, blank=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to="post/", null=True, blank=True)
    like_user_set = models.ManyToManyField(
        User, blank=True, related_name="likes_user_set", through="Like"
    )
    dislike_user_set = models.ManyToManyField(
        User, blank=True, related_name="dislikes_user_set", through="Dislike"
    )

    def __str__(self):
        return self.title

    @property
    def like_count(self):
        return self.like_user_set.count()

    @property
    def dislike_count(self):
        return self.dislike_user_set.count()


class Comment(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("user", "post")


# 싫어요 모델
class Dislike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("user", "post")

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.utils import timezone
from django.views.decorators.http import require_POST
from django.http import HttpResponse
import json
from django.contrib.auth.decorators import login_required

# Create your views here.
def showmain(request):
    posts = Post.objects.all()
    return render(request, "main/mainpage.html", {"posts": posts})


def post(request):
    posts = Post.objects.all()
    return render(request, "main/post.html", {"posts": posts})


def showhw(request):
    return render(request, "main/show.html")


def introduce(request):
    return render(request, "main/introduce.html")


def detail(request, id):
    post = get_object_or_404(Post, pk=id)
    all_comments = post.comments.all().order_by("-created_at")
    return render(request, "main/detail.html", {"post": post, "comments": all_comments})


def new(request):
    return render(request, "main/new.html")


def create(request):
    new_post = Post()
    new_post.title = request.POST["title"]
    new_post.writer = request.user
    new_post.pub_date = timezone.now()
    new_post.summary = request.POST["summary"]
    new_post.body = request.POST["body"]
    new_post.image = request.FILES.get("image")
    new_post.save()
    return redirect("main:detail", new_post.id)


def edit(request, id):
    edit_post = Post.objects.get(id=id)
    return render(request, "main/edit.html", {"post": edit_post})


def update(request, id):
    update_post = Post.objects.get(id=id)
    update_post.title = request.POST["title"]
    update_post.writer = request.user
    update_post.pub_date = timezone.now()
    update_post.summary = request.POST["summary"]
    update_post.body = request.POST["body"]
    if request.FILES.get("image"):
        update_post.image = request.FILES.get("image")
    update_post.save()
    return redirect("main:detail", update_post.id)


def delete(request, id):
    delete_post = Post.objects.get(id=id)
    delete_post.delete()
    return redirect("main:post")


def create_comment(request, post_id):
    if request.method == "POST":
        post = get_object_or_404(Post, pk=post_id)
        current_user = request.user
        comment_content = request.POST.get("content")
        Comment.objects.create(content=comment_content, writer=current_user, post=post)
    return redirect("main:detail", post_id)


def edit_comment(request, id):
    comment = Comment.objects.get(id=id)
    if request.user == comment.writer:
        return render(request, "main/edit_comment.html", {"comment": comment})
    else:
        return redirect("main:detail", comment.post.id)


def update_comment(request, id):
    comment = Comment.objects.get(id=id)
    comment.content = request.POST.get("content")
    comment.save()
    return redirect("main:detail", comment.post.id)


def delete_comment(request, id):
    comment = Comment.objects.get(id=id)
    if request.user == comment.writer:
        comment.delete()
    return redirect("main:detail", comment.post.id)


@require_POST
@login_required
def like_toggle(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_like, post_like_created = Like.objects.get_or_create(
        user=request.user, post=post
    )

    if not post_like_created:
        post_like.delete()
        result = "like_cancel"
    else:
        result = "like"

    context = {"like_count": post.like_count, "result": result}
    return HttpResponse(json.dumps(context), content_type="application/json")


@require_POST
@login_required
def dislike_toggle(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_dislike, post_dislike_created = Dislike.objects.get_or_create(
        user=request.user, post=post
    )

    if not post_dislike_created:
        post_dislike.delete()
        result = "dislike_cancel"
    else:
        result = "dislike"

    context = {"dislike_count": post.dislike_count, "result": result}
    return HttpResponse(json.dumps(context), content_type="application/json")

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="pagesec">
    <h1>{{post.title}}</h1>
    {% if post.writer %}
        {% if 'user' in post.writer.username %}
            작성자 : <a href="{%url 'users:mypage' post.writer.id%}">{{ post.writer.last_name }} {{ post.writer.first_name }}</a>
        {% else %}
            작성자 : <a href="{%url 'users:mypage' post.writer.id%}">{{ post.writer }}</a>
        {% endif %}
    {% else %}
        작성자 : 알 수 없음
    {% endif %}
    <hr>
    {% if post.image%}
        <p style="display:flex; justify-content: center;">
            <img src="{{ post.image.url }}"  style="width:60%;" alt="사진 나올 곳">
        </p>
    {% endif %}
    {% if post.summary %}
        <h3>{{post.summary}}</h3>
    {% endif %}

    <p><pre>{{post.body}}</pre></p>
    {%if request.user == post.writer%}
        <a href="{%url 'main:edit' post.id %}" class="btn_post">수정하기</a>
        <a href="{%url 'main:delete' post.id %}" class="btn_post">삭제하기</a>
    {%endif%}

    <span href="#" class="like" name ="{{post.id}}" value="Like"> 

        <!-- <!— 만약 유저가 좋아요를 눌렀다면 채운 하트로 변경—> -->
        {% if user in post.like_user_set.all %}
            <div class="alt-service-icon">
                <i class="fas fa-heart" id ="like-icon" style="color:red;"></i>
             </div> 
        <!-- <!— 아니면 비워진 하트—>          -->
        {% else %}
    
            <div class="alt-service-icon">
                 <i class="far fa-heart" id ="like-icon" style="color:red;"></i> 
            </div>
    
         {% endif %}
    
         <span id="likecount-{{ post.id }}" class="alt-services-title font-alt"> 
            좋아요 
            {% if post.like_count == 0 %} 
                0개 
            {% else %}
                {{ post.like_count }}개
            {% endif %}
         </span>
    </span>

    <span href="#" class="dislike" name ="{{post.id}}" value="Dislike"> 

        <!-- <!— 만약 유저가 좋아요를 눌렀다면 채운 하트로 변경—> -->
        {% if user in post.dislike_user_set.all %}
            <div class="alt-service-icon">
                <i class="fas fa-heart" id ="dislike-icon" style="color:black;"></i>
             </div> 
        <!-- <!— 아니면 비워진 하트—>          -->
        {% else %}
    
            <div class="alt-service-icon">
                 <i class="far fa-heart" id ="dislike-icon" style="color:black;"></i> 
            </div>
    
         {% endif %}
    
         <span id="dislikecount-{{ post.id }}" class="alt-services-title font-alt"> 
            싫어요
            {% if post.dislike_count == 0 %} 
                0개 
            {% else %}
                {{ post.dislike_count }}개
            {% endif %}
         </span>
    </span>

    <hr>
    <h5>Comments</h5>
    {%if user.is_authenticated%}
    <div>
        <form action="{%url 'main:create_comment' post.id%}" method="POST">
            {%csrf_token%}
            <textarea name="content" placeholder="댓글내용입력"></textarea>
            <input type="submit" value="확인">
        </form>
    </div>
    {%endif%}

    <div>
        {%for comment in comments%}
        <div>
            {% if comment.writer %}
                {% if 'user' in comment.writer.username %}
                    작성자 : {{ comment.writer.last_name }} {{ comment.writer.first_name }}
                {% else %}
                    작성자 : <a href="{%url 'users:mypage' comment.writer.id%}">{{ comment.writer }}</a>
                {% endif %}
            {% else %}
                작성자 : 알 수 없음
            {% endif %}
            <br>
            댓글 내용:{{comment.content}}
            {%if comment.writer == request.user%}
                <a href="{%url 'main:edit_comment' comment.id %}" class="btn_post">댓글수정</a>
                <a href="{%url 'main:delete_comment' comment.id %}" class="btn_post">댓글삭제</a>
            {%endif%}
        </div><br>
        {%endfor%}
    </div>
</section>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>
    $(".like").click(function(){
        var pk = $(this).attr('name')
    $.ajax({
        type:"POST",
        url: "{% url 'main:like_toggle' post.pk %}",
        data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        dataType: "json",

        success: function(response){
            if (response.like_count == null) {
                alert("로그인이 필요합니다");
                window.location.replace("/accounts/login/");
            }
            else {
                if (response.result == "like") {
                    $('#like-icon').removeClass();
                    $('#like-icon').addClass('fas fa-heart');
                }
                else {
                    $('#like-icon').removeClass();
                    $('#like-icon').addClass('far fa-heart');
                }
                $('#likecount-{{ post.id }}').html('좋아요 '+response.like_count+'개');
            }
        },
        error:function(request,status,error){
            alert('로그인이 필요합니다');
            alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
        },
            })
        })
</script>

<script>
    $(".dislike").click(function(){
        var pk = $(this).attr('name')
    $.ajax({
        type:"POST",
        url: "{% url 'main:dislike_toggle' post.pk %}",
        data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        dataType: "json",

        success: function(response){
            if (response.dislike_count == null) {
                alert("로그인이 필요합니다");
                window.location.replace("/accounts/login/");
            }
            else {
                if (response.result == "dislike") {
                    $('#dislike-icon').removeClass();
                    $('#dislike-icon').addClass('fas fa-heart');
                }
                else {
                    $('#dislike-icon').removeClass();
                    $('#dislike-icon').addClass('far fa-heart');
                }
                $('#dislikecount-{{ post.id }}').html('싫어요 '+response.dislike_count+'개');
            }
        },
        error:function(request,status,error){
            alert('로그인이 필요합니다');
            alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
        },
            })
        })
</script>
{% endblock %}

main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form action="{% url 'main:update' post.id %}" method="post" enctype="multipart/form-data">
	{%csrf_token%}
	<p>제목 : <input type="text" name="title" value="{{post.title}}"></p>
	<p>사진 : <input type="file" name="image"></p>
	<p>요약 : <input type="text" name="summary" value="{{post.summary}}"></p>
	<p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10">{{post.body}}</textarea></p>
	<button type="submit">제출</button>
</form>

{% endblock %}

main/templates/main/edit_comment.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form action="{%url 'main:update_comment' comment.id%}" method="POST">
	{%csrf_token%}
	<textarea name="content">{{comment.content}}</textarea>
	<input type="submit" value="확인">
</form>

{% endblock %}

main/templates/main/introduce.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <section class="pagesec">
        <h1>상세 정보</h1>
        <div style="display:flex; justify-content: space-around; margin-top:5vh;">
            <table>
                <tr>
                    <th>사진</th>
                    <td><img src="{% static 'images/intro.jpg'%}" alt="증명사진" class="face"></td>
                </tr>
                <tr>
                    <th>이름</th>
                    <td>박상준</td>
                </tr>
                <tr>
                    <th>생년월일</th>
                    <td>2000년 4월 14일</td>
                </tr>
                <tr>
                    <th>출생지</th>
                    <td>경기도 군포시</td>
                </tr>
                <tr>
                    <th>학교</th>
                    <td>광정초등학교<br>
                        산본중학교<br>
                        용호고등학교<br>
                        동국대학교 정보통신공학전공(주전공)<br>
                        데이터사이언스 소프트웨어(연계전공)</td>
                </tr>
            </table>
            <div style="display:flex; flex-direction: column; ">
                <h4 style="position:relative; left:-5vh;">URLS</h4>
                <br>
                    <a style="color:tomato;" href="https://stujune-to-devjune.tistory.com/" target="_blank">Tistory</a>
                    <a style="color:tomato;" href="https://github.com/tkdwns414" target="_blank">Github</a>
                    <a style="color:tomato;" href="https://www.instagram.com/sjpxxsj/?hl=ko" target="_blank">Instagram</a>
                <br>
                <h4 style="position:relative; left:-5vh;">How to contact</h4>
                <br>
                    <h6 style="position:relative; left:-2vh;">Emails</h6>
                    <span>sangjune2000@naver.com</span>
                    <span>sangjune2000@dogguk.edu</span>
                <br>
                    <h6 style="position:relative; left:-2vh;">Phone num</h6>
                    <span>010-6289-0164</span>

            </div>
        </div>

    </section>
    
{% endblock %}

main/templates/main/mainpage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="pagesec" style="margin:3vh 15vh;">
    <h2 style="display:inline;">Profile</h2>
    <a href="{%url 'main:introduce'%}">more detail</a><br><br>

    <h5>Name: 박상준 (ParkSangJune)</h5>

    <h5>Major:</h5>
    <ul>
        <li>Information Communication Enginerring</li>
        <li>DataScience Software</li>
    </ul>

    <h2>Tech stack</h2>

    <details>
        <summary><h4 style="display:inline;">Langauge</h4></summary>
        <ul>
            <li>JAVA</li>
            <li>Python</li>
            <li>C lang</li>
        </ul>
    </details>
    
    <details>
        <summary><h4 style="display:inline;">Frameworks</h4></summary>
        <ul>
            <li>Django</li>
            <li>Spring Boot</li>
        </ul>
    </details>
    
    <details>
        <summary><h4 style="display:inline;">Others</h4></summary>
        <ul>
            <li>Git & Github</li>
            <li>AWS, RDS</li>
        </ul>
    </details>

    <br>
    <h5><a href="{% static 'files/resume.pdf'%}" target="_blank">박상준 이력서(클릭 시 이동)</a></h5>
    <h6>2021.08.26 에 산업기능요원 시작하여 2022.02.26(최소 기간 6개월)부터 편입 가능</h6>
    <h6>현재 산업 기능 요원 전직(편입) 할 회사 구하는 중입니다</h6>

    <br>
    <h2>Projects</h2>

    {%for post in posts%}
        {%if post.writer.is_superuser%}
            <a href="{%url 'main:detail' post.id%}">
                <div class="home_div1">
                    <div class="home_div2">
                        {%if post.image%}
                            <img src="{{ post.image.url }}" alt="프로젝트 이미지" style="width:100%; padding:3%;">
                        {%else%}
                            <img src="{% static 'images/default.jpg'%}" style="width:100%; padding:3%;">
                        {%endif%}
                    </div>
                    <br>
                    <h4 style="text-align: center;">{{post.title}}</h4>
                </div>
            </a>
        {%endif%}
    {%endfor%}
    
</section>
{% endblock %}

main/templates/main/new.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="pagesec">
	<form action="{%url 'main:create'%}" method="post" enctype="multipart/form-data">
		{%csrf_token%}
		<p>제목 : <input type="text" name="title"></p>
		<p>요약 : <input type="text" name="summary" maxlength="25"></p>
		<p>사진 : <input type="file" name="image"></p>
		<p>내용 : <textarea type="text" name="body" id="" cols="90" rows="10"></textarea></p>
		<button type="submit">제출</button>
	</form>	
</section>

{% endblock %}

main/templates/main/post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="pagesec">
    <h1>글 목록</h1>
    {%if user.is_authenticated%}
    <a href="{%url 'main:new' %}" class="btn_post">새 글쓰기</a>
    {%endif%}

    <div>
        {% for post in posts %}
        <hr>
        <div style="display:flex; margin: 10px 0px; height: 20vh;">
            <div style="overflow:hidden;margin:0px 30px;width:20vh; height:20vh;border:solid black 3px;border-radius:10%; background-color: white;">
            {%if post.image%}
            <!-- 게시글에 따로 이미지가 있었으면 썸네일 제작 -->
                <img src="{{ post.image.url }}" style="object-fit: cover; width:100%; height: 100%;" alt="사진">
            {%else%}
            <!-- 게시글에 따로 이미지가 없을 경우 로고를 썸네일로 -->
                <img src="{% static 'images/default.jpg'%}" style="width:15vh; height:15vh; position:relative; top:2.5vh; left:2.5vh;">
            {%endif%}
            </div>
            <div style="display:flex; flex-direction: column; justify-content: space-evenly;">
                <a href="{%url 'main:detail' post.id%}"><h3 style="font-family: 'Nanum Gothic Coding', sans-serif;">{{post.title}}</h3></a>
                <h5>{{post.summary}}</h5>
                {% if post.writer %}
                    {% if 'user' in post.writer.username %}
                        작성자 : {{ post.writer.last_name }} {{ post.writer.first_name }}
                    {% else %}
                        작성자 : {{ post.writer }}
                    {% endif %}
                {% else %}
                    작성자 : 알 수 없음
                {% endif %}
            </div>
        </div>
        {%endfor%}
    </div>
<!--     

-->
</section>
{% endblock %}

main/templates/main/show.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="pagesec">
    <h1>Just for fun</h1>
    <div style="margin-top: 20vh; display:flex; justify-content: center; align-items: center; flex-direction: column;">
        <span class="forfun"><a href="http://www.dgulion.com/" target="_blank">🦁</a></span>
        <p style="font-size:75px;">click lion!</p>
    </div>
</section>
{% endblock %}