main/urls.py
from django.urls import path
from .views import *

app_name = "main"

urlpatterns = [
    path("", showmain, name="mainpage"),
    path("show/", showhw, name="show"),
    path("introduce/", introduce, name="introduce"),
    path("post/", post, name="post"),
    path("<str:id>", detail, name="detail"),
    path("new/", new, name="new"),
    path("create/", create, name="create"),
    path("edit/<str:id>", edit, name="edit"),
    path("update/<str:id>", update, name="update"),
    path("delete/<str:id>", delete, name="delete"),
    path("<str:post_id>/create_comment", create_comment, name="create_comment"),
    path("edit_comment/<str:id>", edit_comment, name="edit_comment"),
    path("update_comment/<str:id>", update_comment, name="update_comment"),
    path("delete_comment/<str:id>", delete_comment, name="delete_comment"),
    path("like_toggle/<str:post_id>", like_toggle, name="like_toggle"),
    path("dislike_toggle/<str:post_id>", dislike_toggle, name="dislike_toggle"),
]

sns_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include("allauth.urls")),
    path("users/", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = "users"

urlpatterns = [
    path("<int:id>/mypage", views.mypage, name="mypage"),
    path("<int:id>/follow", views.follow, name="follow"),
]

sns_project/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'main:mainpage'%}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main:post'%}">Posts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'main:introduce'%}">About me</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              More Action
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{%url 'main:show'%}">Show</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Not update yet</a></li>
            </ul>
          </li><li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% if request.user.is_authenticated %}
              <li><a class="dropdown-item" href="{%url 'users:mypage' request.user.id %}">Mypage</a></li>
              <li><a class="dropdown-item" href="{%url 'account_logout'%}">Logout</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{%url 'account_login'%}">Login</a></li>
              <li><a class="dropdown-item" href="{%url 'account_signup'%}">Signup</a></li>
              {% endif %}
            </ul>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
</nav>